// Central checklist source used by the on-screen Test Checklist and generated PDF report.
export const tests = [
  "IP Address can be updated and saved",
  "Subnet Mask can be updated and saved",
  "Gateway can be updated and saved",
  "Device is responsive via PING test",
  "Enroll User Function is working",
  "Default ADMIN accounts working",
  "Auto Test Run All working",
  "LCD Test",
  "Voice Test",
  "FP Reader Test",
  "Keypad Test",
  "Face Test",
  "Touch Screen Working",
  "Connected in JPS",
  "Activation key working",
  "Time in/out test",
  "Download logs",
  "Copy DB -> device",
  "Copy device -> DB",
  "Timelogs syncing",
  "Compatibility check",
  "Has ADMS",
  "ADMS via LAN",
  "ADMS via WiFi",
  "Real-time logs",
  "Offline logs test",
  "ADMS icon connected",
  "Has Alphanumeric",
  "Has RFID",
  "Edit User Name",
  "Date/time after restart",
  "Domain in ADMS",
  "Fingerprint capacity",
  "Adapter working",
  "Battery working",
  "Printed manual",
  "Pinwidth change",
  "Editing Role",
  "USB port working",
  "HTTP working",
  "HTTPS working",
];
