-- Endivio baseline schema.
-- Run this first for a new Supabase project, then run later numbered migrations in order.

create extension if not exists pgcrypto;

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  client_code text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists clients_client_code_unique
on public.clients (lower(client_code));

create table if not exists public.statuses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#4b5563',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.device_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists device_types_name_unique
on public.device_types (lower(name));

create table if not exists public.device_inventory_items (
  id bigint generated by default as identity primary key,
  company text,
  client_id bigint references public.clients(id) on delete set null,
  raised_by text,
  date_received date,
  package_style text,
  cst_number text,
  ticket_number text,
  sn_number text,
  device_type text,
  with_adapter text,
  start_repairing_support date,
  end_date_support date,
  start_qa date,
  end_date_qa date,
  status_id bigint references public.statuses(id) on delete set null,
  date_delivered date,
  give_to text,
  remarks text,
  source_ongoing_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists device_inventory_items_client_id_idx on public.device_inventory_items(client_id);
create index if not exists device_inventory_items_status_id_idx on public.device_inventory_items(status_id);
create index if not exists device_inventory_items_date_received_idx on public.device_inventory_items(date_received);

create table if not exists public.ongoing_testing_items (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete set null,
  date_received date,
  package_style text,
  picture_url text,
  model text,
  with_adapter text,
  serial_number text,
  start_repairing_support date,
  end_date_support date,
  start_qa date,
  end_date_qa date,
  status_id bigint references public.statuses(id) on delete set null,
  repair_by text,
  test_by text,
  senior_test_by text,
  remarks text,
  source_inventory_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists ongoing_testing_items_client_id_idx on public.ongoing_testing_items(client_id);
create index if not exists ongoing_testing_items_status_id_idx on public.ongoing_testing_items(status_id);
create index if not exists ongoing_testing_items_date_received_idx on public.ongoing_testing_items(date_received);
create unique index if not exists ongoing_testing_items_source_inventory_id_uidx
on public.ongoing_testing_items(source_inventory_id)
where source_inventory_id is not null;

create table if not exists public.repair_device_records (
  id bigint generated by default as identity primary key,
  source_inventory_id bigint references public.device_inventory_items(id) on delete cascade,
  company text,
  client_id bigint references public.clients(id) on delete set null,
  client_code text,
  date_received date,
  package_style text,
  cst_number text,
  ticket_number text,
  sn_number text,
  device_type text,
  with_adapter text,
  workflow_status text not null default 'Repair By',
  assigned_to uuid,
  assigned_to_email text,
  assigned_at timestamptz,
  device_algorithm text,
  device_pinwidth text,
  previous_pinwidth text,
  checking_remarks text,
  test_results jsonb not null default '[]'::jsonb,
  repair_by text,
  test_by text,
  senior_test_by text,
  additional_comments text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create unique index if not exists repair_device_records_source_inventory_id_uidx
on public.repair_device_records(source_inventory_id)
where source_inventory_id is not null;

create table if not exists public.archived_records (
  id uuid primary key default gen_random_uuid(),
  source_table text not null,
  record_type text not null,
  record_label text,
  record_data jsonb not null,
  archived_by uuid,
  archived_at timestamptz not null default now()
);

create table if not exists public.audit_trail (
  id uuid primary key default gen_random_uuid(),
  module text not null,
  action text not null,
  entity_table text,
  entity_id text,
  record_label text,
  summary text,
  before_data jsonb,
  after_data jsonb,
  actor_id uuid,
  actor_email text,
  created_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id uuid primary key,
  email text not null,
  display_name text not null default '',
  is_active boolean not null default true,
  access_rights jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create table if not exists public.release_notes (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  content text not null default '',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists release_notes_created_at_idx on public.release_notes(created_at desc);

alter table public.clients enable row level security;
alter table public.statuses enable row level security;
alter table public.device_types enable row level security;
alter table public.device_inventory_items enable row level security;
alter table public.ongoing_testing_items enable row level security;
alter table public.repair_device_records enable row level security;
alter table public.archived_records enable row level security;
alter table public.audit_trail enable row level security;
alter table public.app_users enable row level security;
alter table public.release_notes enable row level security;

create policy "authenticated users can read clients" on public.clients for select to authenticated using (true);
create policy "authenticated users can manage clients" on public.clients for all to authenticated using (true) with check (true);
create policy "authenticated users can read statuses" on public.statuses for select to authenticated using (true);
create policy "authenticated users can manage statuses" on public.statuses for all to authenticated using (true) with check (true);
create policy "authenticated users can read device types" on public.device_types for select to authenticated using (true);
create policy "authenticated users can manage device types" on public.device_types for all to authenticated using (true) with check (true);
create policy "authenticated users can read device inventory" on public.device_inventory_items for select to authenticated using (true);
create policy "authenticated users can manage device inventory" on public.device_inventory_items for all to authenticated using (true) with check (true);
create policy "authenticated users can read ongoing testing" on public.ongoing_testing_items for select to authenticated using (true);
create policy "authenticated users can manage ongoing testing" on public.ongoing_testing_items for all to authenticated using (true) with check (true);
create policy "authenticated users can read repair device records" on public.repair_device_records for select to authenticated using (true);
create policy "authenticated users can manage repair device records" on public.repair_device_records for all to authenticated using (true) with check (true);
create policy "authenticated users can read archived records" on public.archived_records for select to authenticated using (true);
create policy "authenticated users can manage archived records" on public.archived_records for all to authenticated using (true) with check (true);
create policy "authenticated users can read audit trail" on public.audit_trail for select to authenticated using (true);
create policy "authenticated users can insert audit trail" on public.audit_trail for insert to authenticated with check (true);
create policy "authenticated users can read app users" on public.app_users for select to authenticated using (true);
create policy "authenticated users can insert own app user" on public.app_users for insert to authenticated with check (id = auth.uid());
create policy "authenticated users can update app users" on public.app_users for update to authenticated using (true) with check (true);
create policy "authenticated users can read release notes" on public.release_notes for select to authenticated using (true);
create policy "authenticated users can manage release notes" on public.release_notes for all to authenticated using (true) with check (true);

insert into public.statuses (name, color)
values
  ('Completed', '#00d000'),
  ('N/A', '#475569'),
  ('Ongoing Support', '#f59e0b'),
  ('Overdue Support', '#dc2626'),
  ('Ongoing QA', '#2563eb'),
  ('Ongoing Repair', '#fb923c'),
  ('Cancelled', '#dc2626'),
  ('Deployed', '#00d000')
on conflict (name) do nothing;

insert into public.device_types (name)
values ('T10K'), ('T2200'), ('FaceID 1500')
on conflict (name) do nothing;
