-- Device Monitoring (Spare Parts) schema.

create table if not exists public.spare_parts_statuses (
  id bigint generated by default as identity primary key,
  name text not null unique,
  color text not null default '#4b5563',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.spare_parts_inventory (
  id bigint generated by default as identity primary key,
  device_type_id bigint references public.device_types(id) on delete set null,
  box_serial_number text,
  client_id bigint references public.clients(id) on delete set null,
  status text,
  date_received date,
  remarks text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists spare_parts_inventory_device_type_id_idx on public.spare_parts_inventory(device_type_id);
create index if not exists spare_parts_inventory_client_id_idx on public.spare_parts_inventory(client_id);
create index if not exists spare_parts_inventory_date_received_idx on public.spare_parts_inventory(date_received);

alter table public.spare_parts_statuses enable row level security;
alter table public.spare_parts_inventory enable row level security;

drop policy if exists "Authenticated users can read spare parts statuses" on public.spare_parts_statuses;
create policy "Authenticated users can read spare parts statuses"
on public.spare_parts_statuses for select to authenticated using (true);

drop policy if exists "Authenticated users can manage spare parts statuses" on public.spare_parts_statuses;
create policy "Authenticated users can manage spare parts statuses"
on public.spare_parts_statuses for all to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can read spare parts inventory" on public.spare_parts_inventory;
create policy "Authenticated users can read spare parts inventory"
on public.spare_parts_inventory for select to authenticated using (true);

drop policy if exists "Authenticated users can manage spare parts inventory" on public.spare_parts_inventory;
create policy "Authenticated users can manage spare parts inventory"
on public.spare_parts_inventory for all to authenticated using (true) with check (true);

insert into public.spare_parts_statuses (name, color, is_active)
values
  ('Available', '#16a34a', true),
  ('In Use', '#2563eb', true),
  ('Defective', '#dc2626', true)
on conflict (name) do nothing;
